version: "3.9"
services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && python manage.py runserver 0.0.0.0:8000"
    # command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13.0-alpine
    container_name: db
    restart: always
    command: -p 5434
    env_file:
      - .env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: