version: "3.9"
services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_DEBUG=0
      - POSTGRES_PORT=5434
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && python manage.py runserver 0.0.0.0:8000"
    # command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13.0-alpine
    container_name: db
    restart: always
    command: -p 5434
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_PORT=5434
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: