# Generated by Django 4.0.5 on 2023-01-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('user_id', models.CharField(blank=True, max_length=150)),
                ('flag', models.BooleanField()),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sql.sqlserver')),
            ],
        ),
    ]
